plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'org.jetbrains.kotlin.plugin.serialization'
    id 'dagger.hilt.android.plugin'
    id 'kotlin-parcelize'
}


android {
    compileSdkVersion 34
    flavorDimensions "default"
    namespace = "com.composetemplate"
    defaultConfig {
        applicationId "com.composetemplate"
        minSdkVersion 23
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"

        manifestPlaceholders = [
                appId : keys.appId,
                apiKey: keys.apiKey
        ]

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildFeatures {
        viewBinding true
        compose true
        buildConfig true
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            // Enable R8 full mode
            proguardFiles += ['proguard-rules-r8-full.pro']
        }
        debug {
            minifyEnabled false
            applicationIdSuffix ".debug"
        }
    }

    productFlavors {
        dev {
            dimension "default"
            applicationIdSuffix ".dev"
            manifestPlaceholders = [
                    APP_NAME: "ComposeTemplateDev",
                    env     : "staging"
            ]
            buildConfigField "String", "API_URL", "\"https://pokeapi.co/api/v2/\""
            android.buildFeatures.buildConfig true
        }
        staging {
            dimension "default"
            applicationIdSuffix ".staging"
            //signingConfig signingConfigs.staging
            manifestPlaceholders = [
                    APP_NAME: "ComposeTemplateStaging",
                    env     : "staging"
            ]
            buildConfigField "String", "API_URL", "\"https://reqres.in/api/\""
        }
        production {
            dimension "default"
            //signingConfig signingConfigs.production
            manifestPlaceholders = [
                    APP_NAME: "ComposeTemplate",
                    env     : "production"
            ]
            buildConfigField "String", "API_URL", "\"https://reqres.in/api/\""
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.8"
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    
    packaging {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}


dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib:${versions.kotlin}")

    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:${versions.coroutines}"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:${versions.coroutines}"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:${versions.json}"
    implementation "androidx.core:core-ktx:${versions.ktx_core}"
    implementation "androidx.appcompat:appcompat:${versions.appcompat}"
    
    // Material 3
    implementation "androidx.compose.material3:material3:${versions.material3}"
    implementation "androidx.compose.material3:material3-window-size-class:${versions.material3}"
    
    // Compose
    implementation "androidx.compose.ui:ui:${versions.compose}"
    implementation "androidx.compose.foundation:foundation:${versions.compose}"
    implementation "androidx.compose.runtime:runtime-livedata:${versions.compose}"
    implementation "androidx.compose.ui:ui-tooling:${versions.compose}"
    implementation "androidx.compose.runtime:runtime:${versions.compose}"
    implementation "androidx.activity:activity-compose:${versions.compose}"
    implementation "androidx.compose.compiler:compiler:1.5.15"
    
    // Navigation
    implementation("androidx.navigation:navigation-compose:2.8.8")
    implementation "androidx.hilt:hilt-navigation-compose:${versions.hilt_navigation_compose}"
    
    // Accompanist
    implementation "com.google.accompanist:accompanist-systemuicontroller:0.32.0"
    implementation "com.google.accompanist:accompanist-flowlayout:${versions.accompanist}"
    
    // Networking
    implementation("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:${versions.retrofit_converter}")
    implementation("com.squareup.retrofit2:retrofit:${versions.retrofit}")
    implementation("com.squareup.okhttp3:logging-interceptor:${versions.okhttp}")
    implementation "com.squareup.retrofit2:converter-gson:2.9.0"
    
    // Lifecycle
    implementation("androidx.lifecycle:lifecycle-livedata-core-ktx:${versions.lifecycle}")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:${versions.lifecycle}")
    implementation("androidx.lifecycle:lifecycle-common-java8:${versions.lifecycle}")
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:${versions.lifecycle}")
    implementation("androidx.lifecycle:lifecycle-livedata-ktx:${versions.lifecycle}")
    implementation "androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0"
    
    // Room
    implementation "androidx.room:room-ktx:${versions.room}"
    implementation 'androidx.room:room-paging:2.6.1'
    kapt "androidx.room:room-compiler:${versions.room}"
    
    // Paging
    implementation "androidx.paging:paging-runtime-ktx:3.3.0-alpha02"
    implementation "androidx.paging:paging-compose:${versions.paging_compose}"
    
    // Image loading
    implementation("io.coil-kt:coil-compose:2.5.0")
    
    // DI
    implementation "com.google.dagger:hilt-android:${versions.hilt}"
    kapt "com.google.dagger:hilt-compiler:${versions.hilt}"
    
    // Other
    implementation "androidx.core:core-splashscreen:${versions.splash_screen}"
    implementation("androidx.datastore:datastore-preferences:${versions.datastore}")
    implementation "com.jakewharton.timber:timber:${versions.timber}"
    
    // Testing
    testImplementation "junit:junit:${versions.junit}"
    androidTestImplementation "androidx.test.ext:junit:${versions.junit_ext}"
    androidTestImplementation "androidx.test.espresso:espresso-core:${versions.espresso}"
}