package com.monstarlab.features.nstack

import dk.nodes.nstack.kotlin.NStack

/**
 * Generated by the NStack gradle plugin
 */
object RateReminderActions {

	private const val CRASH = "crash"
	private const val DONATED = "donated"
	private const val FIRSTACTION = "firstaction"
	private const val SECONDACTION = "secondaction"

	suspend fun crash() {
		send(CRASH)
	}

	suspend fun donated() {
		send(DONATED)
	}

	suspend fun firstaction() {
		send(FIRSTACTION)
	}

	suspend fun secondaction() {
		send(SECONDACTION)
	}

	private suspend fun send(action: String) {
		NStack.RateReminder.action(action)
	}
}
